ABCD-ReproNim/materials

_layouts/post.html
This PR partially resolves #2 by adding a single line description of the Q&A docs.
=> ENH: Add description of the Q&A doc

_layouts/post.html
Changed some of the language in the intro template upon request by @angielaird
=> updated header text to template

_posts/2020-10-23-week-2.md
Added Week 2 Q&A webinar recording to Week 2 materials page.
=> Week 2 Instructor Q&A recording added

_layouts/post.html, _posts/2020-10-30-week-3.md
Loop through slide sets and videos for the ReproNim and ABCD lectures, independently.
=> Allow lists for videos and slides.

_posts/2020-10-30-week-3.md
Added the extra demo video for Week 3 and included a pdf of the demo video slides.
=> Add week 3 demo video + slides

_posts/2020-10-30-week-3.md
=> added Week 3 quiz

_posts/2020-10-30-week-3.md
=> update week 3 quiz link

_posts/2020-10-30-week-3.md
added recording of Week 3 Instructor Q&A
=> Add Week 3 Instructor Q&A recording

_posts/2020-11-06-week-4.md
Added link to week 4 quiz for observer stduents
=> add Week 4 quiz

_posts/2020-11-06-week-4.md
add FAIR slides and include boiRxiv link to reading
=> add FAIR slides and include boiRxiv link to reading

_posts/2020-11-13-week-5.md
Added slides for the Week 5 abcd lecture
=> added week 5 abcd lecture slides

_posts/2020-11-06-week-4.md
Added a week 4 special annoucement about the additional JupyterHub and ABCD Data Access quizzes.
=> Added week 4 special announcement

_posts/2020-11-13-week-5.md
add week 4 Q&A and NDA presentation video
=> add Week 4 Q&A and NDA presentation video

_posts/2020-11-13-week-5.md
Add week 5 exercise and ReproNim lecture slides
=> Add week 5 exercise and ReproNim lecture slides

_layouts/main.html, _layouts/resources.html, assets/css/main.css, index.html, misc/_posts/2015-10-10-resources.md
Closes #18. I still need to figure out content and formatting.
Changes proposed:
- Add new page (resources) with links to useful resources.
- Add new page to sidebar as well.
- Some new CSS classes to handle formatting for the sidebar and resources page.
=> Add resources page

_posts/2020-11-13-week-5.md
=> Add Week 5 Q&A

_posts/2020-11-20-week-6.md
=> Add week 6 exercises

_posts/2020-11-20-week-6.md
=> add week 6 Instrctor Q&A video

_posts/2021-01-15-week-7.md, _posts/2021-01-22-week-8.md, _posts/2021-01-29-week-9.md, _posts/2021-02-05-week-10.md, _posts/2021-02-12-week-11.md, _posts/2021-02-19-week-12.md, _posts/template.md
We still need the following:
- Reading links and names
- Various videos and slides.
=> Add materials for weeks 07-12

_posts/2021-01-15-week-7.md
=> update ReproNim video link

_posts/2021-01-15-week-7.md
Add slides fot the week 7 abcd lecture
=> Add week 7 abcd slides

_posts/2021-01-15-week-7.md
Add JB Poline's lecture slides
=> Add ReproNim slides

_posts/2021-01-15-week-7.md
add link for week 7 quiz for observer students
=> Add Week 7 quiz

_layouts/main.html
Add links to project week page and session 1 survey to sidebar.
=> Add sidebar links

_layouts/main.html, misc/_posts/2021-01-11-project-week-data-exercises.md
This fixes the links (hopefully). Can't render locally for some dependency-related reason.
=> Fix sidebar links

misc/_posts/2021-01-11-project-week-data-exercises.md
=> Fix the format of the project week data exercises page.

_posts/2021-01-22-week-8.md
add embedded youtube link to abcd video
=> add abcd video link

_posts/2021-01-15-week-7.md
Add the embedded youtube link to the Week 7 Q&A
=> add Week 7 Q&A video link

_posts/2021-01-22-week-8.md
Add slides for week 8 ABCD lecture
=> Add ABCD wk8 slides

_posts/2021-01-22-week-8.md
=> Add Week 8 quiz link

_posts/2021-01-22-week-8.md
add link to the DataLad ABCD hanbook referenced in the ReproNim lecture
=> Add DataLad ABCD handbook reading

_posts/2021-02-05-week-10.md
Add Novel Tech video and a pdf of slides; Update ReproNim video title
=> Add week 10 video & slides. Update ReproNim title to ReproMan

_posts/2021-01-22-week-8.md
Add link to the Week 8 Instructor Q&A video
=> Add Week 8 Q&A video

_posts/2021-01-29-week-9.md
updated link location for the week 9 ABCD slides
=> Fix link to week 9 abcd slides

_posts/2021-01-29-week-9.md
Link to the slides from @satra's lecture
=> Add @satra's lecture slides

_posts/2021-01-29-week-9.md, misc/_posts/2021-01-11-project-week-data-exercises.md
Add links to the Week 9 quiz and the Project Week Prep Data Exercise: Part 3
=> Week 9 updates

misc/_posts/2021-01-11-project-week-data-exercises.md
minor text edits to Project Week Data Exercises side tab
=> minor text edits

_posts/2021-02-05-week-10.md
fix week 10 abcd slides link (pointed to week 9 abcd slides)
=> update incorrect link in week 10

_posts/2021-02-05-week-10.md
=> Week 10 updates

_posts/2021-02-05-week-10.md
attempting to replace the auto "Readings (to be added)" text with text that reads "No readings for this week's ReproNim elcture". Not sure if my edits match the needed format to make this change.
=> Attempting to add note on there being no ReprMan readings

_posts/2021-02-12-week-11.md
Week 11 updates: week 11 lecture videos, readings, slides + week 10 Q&A webinar video. Still need to add link to week 11 repronim slides (don't have yet).
=> add wk 11 videos, readings, slides; add wk 10 Q&A video

_posts/2021-02-12-week-11.md, _posts/2021-02-19-week-12.md, misc/_posts/2021-01-11-project-week-data-exercises.md
Added week 11 Q&A video, week 12 data exercise link, and project week prep part 4 data exercise link/info
=> added wk11 Q&A vid, wk12 quiz, and proj week prep part 4 exercise

_posts/2021-02-19-week-12.md
=> Add wk12 Q&A video link

Gemfile, _posts/2021-02-19-week-12.md, _posts/2021-02-26-week-13.md, _posts/2021-02-27-project-week.md, index.html
=> Add pages for Week 13 and project week

_posts/2021-02-27-project-week.md
Add schedule and relevant links to the Project Week page
=> Add info to Project Week tab

_posts/2021-02-26-week-13.md
Added links to recording of the Project Week Gather.Town kickoff as well as a link to the recording of the Week 13 Q&A Project Pitches
=> Add link to the Project Week kickoff video and the wk 13 Q&A video link

.circleci/config.yml
I mean, this is exactly the same as #89! 🤣
Changes proposed:
- Checksum based on Gemfile instead of Gemfile.lock.
=> Try to fix the testing issues

_layouts/post.html, _posts/2022-01-10-week-1.md
Merge the previous 2022-week1-updates branch into upstream/main to incorporate circleci fix
=> incorporate ciclecifix into 2022 week 1 updates

.circleci/config.yml, _posts/2022-01-10-week-1.md
Add video and slides for 2022 course overview
=> 2022 week1 updates

_posts/2022-01-10-week-1.md
Change ordering a for better appearance on page
=> Changes to announcement order

_layouts/post.html, _posts/2022-01-10-week-1.md
- Add link to join Slack at the top of the page
- Move the important links and platforms section to be at the bottom of the page
- Add @jessicabartley's video in the week 1 description header
=> Add Slack link in header, move general links to bottom of page

_layouts/post.html
Add spacer to separate Q&A section from links section
=> Add spacer

_layouts/post.html, _posts/2022-01-24-week-3.md
• Add week 3 data exercises
• Add note to all pages that Q&A recording may contain outdated course-related announcements
=> add exercises and update Q&A recording header

_posts/2022-01-31-week-4.md
• Add Week 4 Data Exercise link
• Add DUC confirmation link
• Add announcements (NDA webinar + link, exercise descriptions)
=> week 4 materials page updates

_posts/2022-02-07-week-5.md
• Add Week 5 data exercise, DUC Confirmation link, and JupyterHub Access Form
• Add announcmeents and include a description of the JupyterHub
=> 2022 Week 5 updates

_posts/2022-02-28-aiml-week-1.md
Create the AI/ML Week 1 materials page
=> Create AI/ML Week 1 post

_layouts/post.html, _posts/2022-02-28-aiml-week-1.md
• update post.html coursetype condition to display the second of two lectures for each AI/ML Course week
• Add links to specific pages for AI/ML Lecture 2 readings
=> update post.html coursetype conditional

_layouts/post.html
try hard coding in courtype for if statement and see if that changes the broken posts
=> attemp fix for broken posts

_layouts/post.html
add conditional in the header section to make sure formatting is correct
=> attempt coursetype conditional on a small scale

_layouts/post.html, _posts/2022-02-28-week-8.md
• Add conditionals for AI/ML course lecture 1 material
• Add datalad link to main course week 8 post
=> finally! working! update all ai/ml lecture 1 files

_layouts/post.html
• update title conditionals for ai/ml lectuers 1 and 2
• update all conditional ai/ml content for lecture 2
=> add conditionals for ai/ml lecture 2

misc/_posts/2022-03-01-project-month-data-exercises.md
=> update deader for Project Month Prep Data Exercise 1

_posts/2022-03-14-aiml-week-3.md
... could it be because we have two videos links for the first part?
=> troubleshooting AI/ML wk3 page disappearance

_posts/2022-03-13-aiml-week-3.md
Troubleshooting post dissaparence by adding in fields one by one to search for what is breaking the post:
- Added video and slide linkes
=> ai/ml wk3: add video and slide links

_posts/2022-03-21-aiml-week-4.md
• Add exercise, reading, and video links
• Add announcements section
=> AI/ML Week 4 edits

_posts/2022-03-21-aiml-week-4.md, _posts/2022-03-28-aiml-week-5.md
• Add quotation marks to reading names
• Remove wk 1 assignment links on the wk 5 AI/ML page
=> Fix AI/ML wk 4 page error

_posts/2022-03-21-aiml-week-4.md
Oops forgot one more qotation mark in the wk 4 ai/ml page
=> fix additional error

_posts/2022-04-04-project-month.md
We're now inviting the larger ABCD community!
=> Update Project Month invitation description
